# https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      timezone: 'Europe/Stockholm'
    versioning-strategy: increase
    open-pull-requests-limit: 10
