name: CI

on: [push]

env:
  CI: true
  FORCE_COLOR: 3

jobs:
  test_lint:
    name: Test & Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - uses: actions/checkout@v2

      - name: Set up NPM cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-cache-v0-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-cache-v0-

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Lint
        run: npm run lint
